# Generated by Django 2.2.24 on 2021-07-02 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wereldontdooien.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpublishedFonkel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aangemaakt', models.DateTimeField(auto_now_add=True)),
                ('gewijzigd', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'Spreuk'), (2, 'Tip'), (3, 'Persoonlijke opdracht'), (4, 'Opdracht in gezelschap'), (5, 'Kadootje'), (6, 'Complimentje'), (7, 'Doe-dingen'), (8, 'Recept'), (9, 'Foto-opdracht'), (10, 'Gedicht'), (99, 'Overig')])),
                ('tekst', models.CharField(max_length=1000)),
                ('afbeelding', models.ImageField(upload_to=wereldontdooien.models.imgfile)),
                ('gebruiker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'toekomstige fonkel',
            },
        ),
        migrations.CreateModel(
            name='PublishedFonkel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aangemaakt', models.DateTimeField(auto_now_add=True)),
                ('gewijzigd', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'Spreuk'), (2, 'Tip'), (3, 'Persoonlijke opdracht'), (4, 'Opdracht in gezelschap'), (5, 'Kadootje'), (6, 'Complimentje'), (7, 'Doe-dingen'), (8, 'Recept'), (9, 'Foto-opdracht'), (10, 'Gedicht'), (99, 'Overig')])),
                ('tekst', models.CharField(max_length=1000)),
                ('afbeelding', models.ImageField(upload_to=wereldontdooien.models.imgfile)),
                ('gebruiker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gepubliceerde fonkel',
                'ordering': ['-id'],
            },
        ),
    ]
