#!/usr/bin/env python
from fabric.api import *
from fabric.contrib.files import exists

env.host_string = 'rtts.eu'
env.user = 'www'
local('rsync -av --delete django/ www@rtts.eu:wereldontdooien')

with cd('wereldontdooien'):
    with prefix('workon wereldontdooien'):
        run('yes yes | ./manage.py collectstatic')
        run('./manage.py compilemessages')
        run('./manage.py syncdb')

# Uncomment the following to enable nightly publishing:
#env.user = 'origin'
#if not exists("/etc/cron.d/wereldontdooien"):
#    sudo("echo 'SHELL=/bin/sh' > /etc/cron.d/wereldontdooien")
#    sudo("echo '0 3 * * * %s cd %s && ./publish.sh' >> /etc/cron.d/wereldontdooien" % (user, abspath('django')))
#done()

env.user = 'origin'
sudo('killall -SIGHUP uwsgi')

print "Deployment succeeded!"
