#!/usr/bin/env python
from r2src.deploy import *

host = 'wereldontdooien.nl'
aliases = ['www.wereldontdooien.nl']

bootstrap()
install('python-dev postgresql postgresql-server-dev-all gettext')
setup_virtualenv('wereldontdooien')

explain("Checking /srv/wereldontdooien")
dir_exists('/srv/wereldontdooien') or abort("/srv/wereldontdooien doesn't exist!")
done()

upload()

explain("Collecting static files...")
with cd(abspath('django')):
    vrun('wereldontdooien', './manage.py collectstatic')
done()

explain("Generating locales...")
with cd(abspath('django')):
    vrun('wereldontdooien', './manage.py compilemessages')
done()

explain("Syncing database...")
with cd(abspath('django')):
    vrun('wereldontdooien', './manage.py syncdb')
done()

# Uncomment the following to enable nightly publishing:

explain("Installing crontab...")
if not file_exists("/etc/cron.d/wereldontdooien"):
    sudo("echo 'SHELL=/bin/sh' > /etc/cron.d/wereldontdooien")
    sudo("echo '0 0 * * * %s cd %s && ./publish.sh' >> /etc/cron.d/wereldontdooien" % (user, abspath('django')))
done()

serve_dynamically(host, virtualenv='wereldontdooien', static_dir=abspath('django/static'), chdir=abspath('django'), wsgi_file='project/wsgi.py', aliases=aliases)

done('Deployment complete!')
